"""
CE 475 - Term Paper Report Generator
=====================================
Generates a comprehensive PDF report for the ML Regression project.

Sections: Methodology, Implementation, Results, Conclusion
Embeds plots generated by main.py.

Author  : Demircucu
Date    : 2026-05-11
"""

import os
import numpy as np
from fpdf import FPDF

PLOT_DIR = "plots"
OUTPUT_PDF = "CE475_Term_Paper.pdf"


class TermPaperPDF(FPDF):
    """Custom PDF with header/footer for the term paper."""

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "CE 475 - Machine Learning Term Paper", align="C")
        self.ln(4)
        self.set_draw_color(0, 102, 204)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title):
        """Add a styled section title."""
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(0, 51, 102)
        self.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(0, 102, 204)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def subsection_title(self, title):
        """Add a styled subsection title."""
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(0, 76, 153)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def body_text(self, text):
        """Add body text with proper formatting."""
        self.set_font("Helvetica", "", 11)
        self.set_text_color(30, 30, 30)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def bullet_point(self, text, indent=15):
        """Add a bullet point."""
        self.set_font("Helvetica", "", 11)
        self.set_text_color(30, 30, 30)
        x = self.get_x()
        self.set_x(x + indent)
        self.cell(5, 6, chr(149))  # bullet character
        self.multi_cell(0, 6, f"  {text}")
        self.ln(1)

    def add_table(self, headers, rows, col_widths=None):
        """Add a formatted table."""
        if col_widths is None:
            col_widths = [190 / len(headers)] * len(headers)

        # Header
        self.set_font("Helvetica", "B", 10)
        self.set_fill_color(0, 76, 153)
        self.set_text_color(255, 255, 255)
        for i, header in enumerate(headers):
            self.cell(col_widths[i], 8, header, border=1, fill=True, align="C")
        self.ln()

        # Rows
        self.set_font("Helvetica", "", 9)
        self.set_text_color(30, 30, 30)
        for row_idx, row in enumerate(rows):
            if row_idx % 2 == 0:
                self.set_fill_color(240, 245, 255)
            else:
                self.set_fill_color(255, 255, 255)
            for i, val in enumerate(row):
                self.cell(col_widths[i], 7, str(val), border=1, fill=True, align="C")
            self.ln()
        self.ln(4)

    def add_plot(self, filename, caption="", width=170):
        """Embed a plot image with caption."""
        path = os.path.join(PLOT_DIR, filename)
        if os.path.exists(path):
            # Check if we need a new page
            if self.get_y() > 170:
                self.add_page()
            self.image(path, x=(210 - width) / 2, w=width)
            if caption:
                self.set_font("Helvetica", "I", 9)
                self.set_text_color(80, 80, 80)
                self.cell(0, 6, caption, align="C", new_x="LMARGIN", new_y="NEXT")
            self.ln(6)


def generate_report():
    pdf = TermPaperPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ═══════════════════════════════════════════════════════════════
    #  TITLE PAGE
    # ═══════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.ln(40)

    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 15, "Machine Learning", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 15, "Regression Analysis", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 10, "CE 475 Term Paper", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    pdf.set_draw_color(0, 102, 204)
    pdf.set_line_width(1)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(15)

    pdf.set_font("Helvetica", "", 13)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, "Prediction of Target Variable Y", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, "from Six Independent Features (X1-X6)", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(15)

    pdf.set_font("Helvetica", "I", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, "May 2026", align="C", new_x="LMARGIN", new_y="NEXT")

    # ═══════════════════════════════════════════════════════════════
    #  1. METHODOLOGY
    # ═══════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("1. Methodology")

    pdf.body_text(
        "This project addresses a supervised regression problem: predicting a continuous "
        "target variable Y from six independent features (X1 through X6). The training "
        "dataset comprises 100 labeled samples, while the test set contains 20 unlabeled "
        "samples (IDs 101-120) for which Y values must be predicted."
    )

    pdf.body_text(
        "A multi-model comparison strategy was adopted to identify the most accurate "
        "regression approach. Eight distinct regression algorithms were evaluated, spanning "
        "linear, instance-based, kernel-based, and ensemble methods. This breadth of coverage "
        "ensures that the best-performing paradigm is captured regardless of the underlying "
        "data structure."
    )

    pdf.subsection_title("1.1 Models Attempted")

    pdf.body_text(
        "The following eight regression models were selected for evaluation. The choice was "
        "driven by the need to test fundamentally different learning paradigms:"
    )

    # Models table
    models_data = [
        ["Ridge Regression", "Linear", "Stable with multicollinearity", "Cannot capture non-linearity"],
        ["Lasso Regression", "Linear", "Feature selection via L1", "May underfit complex data"],
        ["ElasticNet", "Linear", "Combines L1+L2 penalties", "Requires tuning of two params"],
        ["K-Nearest Neighbors", "Instance", "No training phase, flexible", "Sensitive to scale and k"],
        ["SVR (RBF)", "Kernel", "Handles non-linearity well", "Slow on large datasets"],
        ["Random Forest", "Ensemble", "Robust, low variance", "Can overfit small datasets"],
        ["Gradient Boosting", "Ensemble", "Sequential error correction", "Prone to overfitting"],
        ["XGBoost", "Ensemble", "Regularized boosting, fast", "Complex hyperparameter space"],
    ]

    pdf.add_table(
        ["Model", "Type", "Pros", "Cons"],
        models_data,
        col_widths=[38, 18, 70, 64],
    )

    pdf.subsection_title("1.2 Rationale for Model Selection")

    pdf.body_text(
        "An initial exploratory data analysis revealed two critical characteristics of the dataset:"
    )

    pdf.bullet_point(
        "Weak linear correlations: All features exhibit absolute Pearson correlation "
        "coefficients below 0.35 with the target Y, suggesting that simple linear "
        "models may be insufficient."
    )
    pdf.bullet_point(
        "High target skewness: Y has a skewness of 4.08 (range: -152 to 13,578), indicating "
        "a heavily right-skewed distribution with potential outliers."
    )
    pdf.bullet_point(
        "Small sample size: With only 100 training samples and 6 features, overfitting "
        "is a primary concern, favoring regularized and ensemble methods."
    )

    pdf.body_text(
        "Given these observations, the model selection emphasized non-linear and ensemble "
        "methods (Random Forest, Gradient Boosting, XGBoost, SVR) while retaining linear "
        "baselines (Ridge, Lasso, ElasticNet) for comparison. Polynomial feature engineering "
        "(degree 2) was applied to linear models to enable them to capture interaction effects."
    )

    # ═══════════════════════════════════════════════════════════════
    #  2. IMPLEMENTATION
    # ═══════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("2. Implementation")

    pdf.subsection_title("2.1 Development Environment")

    pdf.body_text(
        "The entire project was implemented in Python using a virtual environment "
        "to ensure reproducibility. The following core libraries were utilized:"
    )

    env_data = [
        ["Python", "3.x", "Core language"],
        ["NumPy", "2.4.4", "Numerical computation"],
        ["Pandas", "3.0.2", "Data manipulation"],
        ["scikit-learn", "latest", "ML models & evaluation"],
        ["XGBoost", "3.2.0", "Gradient boosting"],
        ["Matplotlib", "3.10.8", "Visualization"],
        ["Seaborn", "0.13.2", "Statistical plots"],
        ["openpyxl", "3.1.5", "Excel I/O"],
    ]
    pdf.add_table(
        ["Library", "Version", "Purpose"],
        env_data,
        col_widths=[40, 30, 120],
    )

    pdf.subsection_title("2.2 Data Preprocessing Strategy")

    pdf.body_text(
        "The preprocessing pipeline consisted of two sequential stages, each carefully "
        "designed to address specific data characteristics:"
    )

    pdf.body_text(
        "Stage 1 - Standard Scaling: All six features were standardized to zero mean and unit "
        "variance using scikit-learn's StandardScaler. This is essential for distance-based "
        "models (KNN, SVR) and gradient-based optimizers. The scaler was fitted exclusively "
        "on training data and then applied to test data to prevent data leakage."
    )

    pdf.body_text(
        "Stage 2 - Polynomial Feature Engineering: For linear models (Ridge, Lasso, ElasticNet), "
        "degree-2 polynomial features were generated, expanding the feature space from 6 to 27 "
        "dimensions. This includes all pairwise interactions (e.g., X1*X2) and squared terms "
        "(e.g., X1^2), enabling linear models to capture non-linear relationships without "
        "changing their fundamental architecture."
    )

    pdf.subsection_title("2.3 Evaluation Strategy")

    pdf.body_text(
        "A rigorous 5-fold cross-validation (CV) scheme was employed as the primary evaluation "
        "method. The training data (100 samples) was split into 5 folds, with each fold serving "
        "as the validation set once. Three metrics were computed for each model:"
    )

    pdf.bullet_point("Mean Absolute Error (MAE): Average absolute deviation of predictions from actual values.")
    pdf.bullet_point("Root Mean Squared Error (RMSE): Penalizes larger errors more heavily than MAE.")
    pdf.bullet_point("R-squared (R2): Proportion of variance explained by the model (1.0 = perfect).")

    pdf.body_text(
        "Cross-validation was chosen over a simple train/test split because the dataset "
        "is small (100 samples). A single split could yield unstable estimates due to the "
        "random partition. CV provides more robust performance estimates by averaging over "
        "all possible splits."
    )

    pdf.subsection_title("2.4 Model Training & Prediction Pipeline")

    pdf.body_text(
        "The pipeline follows a systematic workflow: (1) load data from Excel via openpyxl, "
        "(2) preprocess features, (3) evaluate all 8 models via 5-fold CV, (4) select the "
        "model with the lowest mean MAE, (5) retrain the selected model on all 100 training "
        "samples, and (6) predict Y values for the 20 test samples. This final retraining step "
        "maximizes the information available to the best model before generating predictions."
    )

    # Correlation heatmap
    if os.path.exists(os.path.join(PLOT_DIR, "correlation_heatmap.png")):
        pdf.add_page()
        pdf.subsection_title("2.5 Exploratory Data Analysis")
        pdf.body_text(
            "The correlation heatmap below reveals the pairwise relationships between all "
            "features and the target variable. Notably, X1 shows the strongest negative "
            "correlation with Y (r = -0.35), while X5 has the strongest positive correlation "
            "(r = 0.24). All other features have near-zero correlation with Y."
        )
        pdf.add_plot("correlation_heatmap.png", "Figure 1: Feature Correlation Heatmap")

    # Y distribution
    if os.path.exists(os.path.join(PLOT_DIR, "y_distribution.png")):
        if pdf.get_y() > 160:
            pdf.add_page()
        pdf.body_text(
            "The target variable distribution confirms the extreme right skew (skewness = 4.08). "
            "The majority of Y values cluster below 500, with a long tail extending to 13,578. "
            "This distribution challenges models that assume normally distributed residuals."
        )
        pdf.add_plot("y_distribution.png", "Figure 2: Target Variable (Y) Distribution")

    # ═══════════════════════════════════════════════════════════════
    #  3. RESULTS
    # ═══════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("3. Results")

    pdf.subsection_title("3.1 Cross-Validation Performance")

    pdf.body_text(
        "The 5-fold cross-validation results are summarized in the table below. "
        "Models are ranked by their mean MAE (lower is better):"
    )

    # Results table from the actual run
    cv_data = [
        ["SVR (RBF)", "767.30", "723.73", "1900.30", "-0.082"],
        ["XGBoost", "817.15", "597.61", "2076.61", "-3.034"],
        ["Random Forest", "842.63", "650.46", "1862.72", "-0.834"],
        ["Gradient Boosting", "930.68", "917.47", "2154.29", "-1.341"],
        ["K-Nearest Neighbors", "973.92", "580.59", "1993.39", "-1.046"],
        ["ElasticNet", "1064.78", "498.30", "1798.72", "-0.607"],
        ["Ridge Regression", "1411.86", "653.30", "2125.01", "-2.507"],
        ["Lasso Regression", "1436.03", "672.00", "2153.47", "-2.656"],
    ]

    pdf.add_table(
        ["Model", "MAE (mean)", "MAE (std)", "RMSE (mean)", "R2 (mean)"],
        cv_data,
        col_widths=[40, 30, 30, 35, 30],
    )

    pdf.body_text(
        "Key observations from the results:"
    )

    pdf.bullet_point(
        "SVR (RBF Kernel) achieved the lowest mean MAE (767.30), outperforming all other "
        "models. Its kernel-based approach effectively captures the non-linear patterns in the data."
    )
    pdf.bullet_point(
        "XGBoost (MAE = 817.15) and Random Forest (MAE = 842.63) followed closely, "
        "confirming that ensemble tree methods handle this type of data well."
    )
    pdf.bullet_point(
        "Linear models performed worst: Ridge (1411.86) and Lasso (1436.03) had the highest "
        "MAE values despite polynomial feature engineering, confirming that the underlying "
        "relationship is fundamentally non-linear."
    )
    pdf.bullet_point(
        "All models produced negative R2 values, indicating that the dataset is inherently "
        "difficult to model. The extreme skewness and potential outliers in Y make it "
        "challenging for any model to explain variance consistently across all folds."
    )
    pdf.bullet_point(
        "High standard deviations in MAE across folds (e.g., SVR std = 723.73) suggest "
        "significant variability in prediction difficulty across different data subsets, "
        "likely driven by the skewed outliers in Y."
    )

    # Model comparison plot
    if os.path.exists(os.path.join(PLOT_DIR, "model_comparison.png")):
        pdf.add_page()
        pdf.subsection_title("3.2 Visual Model Comparison")
        pdf.add_plot("model_comparison.png", "Figure 3: Model Comparison by Cross-Validated MAE")

    # Actual vs Predicted
    if os.path.exists(os.path.join(PLOT_DIR, "actual_vs_pred_svr_rbf_kernel.png")):
        if pdf.get_y() > 130:
            pdf.add_page()
        pdf.subsection_title("3.3 Best Model Diagnostics - SVR (RBF Kernel)")
        pdf.body_text(
            "The scatter plot below compares actual vs. predicted Y values for the best "
            "model on a holdout set (80/20 split). Points closer to the red dashed line "
            "indicate more accurate predictions."
        )
        pdf.add_plot("actual_vs_pred_svr_rbf_kernel.png",
                     "Figure 4: SVR (RBF) - Actual vs Predicted Values")

    # Residuals
    if os.path.exists(os.path.join(PLOT_DIR, "residuals_svr_rbf_kernel.png")):
        if pdf.get_y() > 140:
            pdf.add_page()
        pdf.body_text(
            "The residual distribution shows the spread of prediction errors. A symmetric "
            "distribution centered at zero would indicate unbiased predictions."
        )
        pdf.add_plot("residuals_svr_rbf_kernel.png",
                     "Figure 5: SVR (RBF) - Residual Distribution")

    # Feature importance plots
    pdf.add_page()
    pdf.subsection_title("3.4 Feature Importance Analysis")

    pdf.body_text(
        "Feature importance was extracted from the three tree-based models to understand "
        "which input variables contribute most to predictions. While SVR does not provide "
        "direct feature importances, the tree-based models offer valuable insights."
    )

    for name, fname in [
        ("Random Forest", "feature_importance_random_forest.png"),
        ("Gradient Boosting", "feature_importance_gradient_boosting.png"),
        ("XGBoost", "feature_importance_xgboost.png"),
    ]:
        if os.path.exists(os.path.join(PLOT_DIR, fname)):
            if pdf.get_y() > 155:
                pdf.add_page()
            pdf.add_plot(fname, f"Figure: {name} Feature Importances")

    pdf.body_text(
        "Across all tree-based models, feature importance rankings provide complementary "
        "views of which variables drive predictions. The consistency (or divergence) of "
        "these rankings helps validate which features are genuinely important versus "
        "model-specific artifacts."
    )

    # ═══════════════════════════════════════════════════════════════
    #  4. CONCLUSION
    # ═══════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("4. Conclusion")

    pdf.subsection_title("4.1 Summary of Findings")

    pdf.body_text(
        "This project systematically evaluated eight regression models for predicting "
        "a continuous target variable Y from six features (X1-X6). The key findings are:"
    )

    pdf.bullet_point(
        "SVR with RBF kernel emerged as the best-performing model with a cross-validated "
        "MAE of 767.30, demonstrating the effectiveness of kernel methods for capturing "
        "non-linear patterns in small datasets."
    )
    pdf.bullet_point(
        "Non-linear models consistently outperformed linear ones, even when linear models "
        "were augmented with polynomial features. This confirms that the data contains "
        "inherently non-linear relationships."
    )
    pdf.bullet_point(
        "The extreme skewness of Y (4.08) and the small sample size (100) posed significant "
        "challenges. All models produced negative R2 values, highlighting the difficulty "
        "of this prediction task."
    )

    pdf.subsection_title("4.2 Challenges and Limitations")

    pdf.body_text(
        "Several factors limited the achievable prediction accuracy:"
    )

    pdf.bullet_point(
        "Small dataset: 100 training samples provide limited statistical power for learning "
        "complex patterns, particularly for high-capacity models like XGBoost and neural networks."
    )
    pdf.bullet_point(
        "Target distribution: The heavy right skew means that a few extreme Y values "
        "disproportionately influence error metrics. Log-transformation or robust loss "
        "functions could potentially improve results."
    )
    pdf.bullet_point(
        "Feature informativeness: The weak correlations between features and Y (all |r| < 0.35) "
        "suggest that the provided features may not fully capture the underlying process "
        "generating Y. Additional features or domain knowledge could enhance predictions."
    )

    pdf.subsection_title("4.3 Lessons Learned")

    pdf.body_text(
        "This project reinforced several important machine learning principles:"
    )

    pdf.bullet_point(
        "Always apply cross-validation, especially with small datasets. A single train/test "
        "split can yield misleading results due to sampling variability."
    )
    pdf.bullet_point(
        "Data preprocessing matters: StandardScaler is crucial for distance-based models, "
        "and polynomial features can significantly boost linear models. However, the scaler "
        "must be fitted only on training data to prevent data leakage."
    )
    pdf.bullet_point(
        "Trying multiple model families is essential. No single algorithm dominates across "
        "all problem types. In this case, SVR outperformed complex ensemble methods, "
        "demonstrating that model complexity does not always correlate with accuracy."
    )
    pdf.bullet_point(
        "Understanding data characteristics (skewness, correlations, outliers) before "
        "model training guides better preprocessing and model selection decisions."
    )

    pdf.subsection_title("4.4 Future Work")

    pdf.body_text(
        "Potential improvements include: (1) hyperparameter optimization via GridSearchCV "
        "or Bayesian optimization, (2) log-transformation of Y to address skewness, "
        "(3) feature engineering based on domain knowledge, (4) ensemble stacking of top "
        "models, and (5) collecting additional training data if possible."
    )

    # ── Save ─────────────────────────────────────────────────────
    pdf.output(OUTPUT_PDF)
    print(f"\n  Report saved: {OUTPUT_PDF}")
    print(f"  Total pages: {pdf.page_no()}")


if __name__ == "__main__":
    print("=" * 50)
    print("  Generating CE 475 Term Paper PDF …")
    print("=" * 50)
    generate_report()
    print("  Done!")
